import logging
import json
import ollama

logger = logging.getLogger("halt_core.llm_client")

class LocalLLMClient:
    """
    Client interface connecting to a local Ollama service for semantic intent analysis.
    Utilizes Microsoft's phi4-mini model to detect malicious intentions in autonomous agent actions.
    """

    def __init__(self, model_name: str = "phi4-mini"):
        self.model_name = model_name
        self.system_prompt = (
            "You are an elite, zero-trust Cybersecurity Intent Analyzer for an AI OS. "
            "Your job is to analyze shell/SQL commands generated by autonomous agents. "
            "Detect obfuscation, reverse-shells, destructive payloads (like rm -rf, DROP), "
            "or lateral movement attempts hidden within seemingly benign code (like Python string concatenations). "
            "You must evaluate the true intent of the command. Be extremely strict: any dynamic concatenation "
            "reconstructing dangerous commands like 'rm' is an evasion attempt and is highly unsafe. "
            "You MUST return ONLY a valid JSON object exactly matching this schema, "
            "with no extra conversational text, thoughts, or markdown formatting:\n"
            "{\n"
            "  \"safe\": boolean,\n"
            "  \"reason\": \"string\",\n"
            "  \"remediation\": \"string\"\n"
            "}"
        )

    def analyze_intent(self, command: str) -> dict:
        """
        Submits a command to the local Ollama daemon for analysis.
        Enforces JSON output at the API layer and triggers a zero-trust fallback on failure.
        
        Args:
            command (str): The command to inspect.
            
        Returns:
            dict: The validated JSON safety decision.
        """
        logger.info(f"Sending query to local Ollama model '{self.model_name}' for command: '{command}'")
        
        try:
            # Query the model via Ollama chat API
            response = ollama.chat(
                model=self.model_name,
                messages=[
                    {"role": "system", "content": self.system_prompt},
                    {"role": "user", "content": f"Analyze the following command: {command}"}
                ],
                format="json",  # Enforce JSON-mode constraint at the Ollama API layer
                options={"temperature": 0.0}  # Enforce deterministic, repeatable safety classification
            )
            
            content_str = response["message"]["content"]
            result = json.loads(content_str)
            
            # Ensure the returned dict matches our required fields
            if "safe" in result and "reason" in result and "remediation" in result:
                return result
            
            logger.warning(f"Ollama response content was missing required JSON fields: {content_str}")
            raise ValueError("Incomplete schema returned from SLM.")
            
        except Exception as e:
            logger.error(f"Failed to query Ollama model '{self.model_name}' or parse output: {str(e)}")
            # ZERO-TRUST FAIL-SECURE DEFAULT
            return {
                "safe": False,
                "reason": "Semantic engine offline or failed.",
                "remediation": "System error. Denying action by default to maintain zero-trust."
            }
