from fastapi import FastAPI
from halt_core.models.schemas import AgentAction, SecurityDecision
from halt_core.interceptor.engine import RuleEngine
from halt_core.interceptor.rules.sql_rules import SQLDenyListRule
from halt_core.interceptor.rules.shell_rules import ShellDenyListRule
from halt_core.interceptor.rules.stateful_rules import SuspiciousSequenceRule
from halt_core.interceptor.rules.semantic_rules import SemanticIntentRule
from halt_core.interceptor.memory import MemoryManager
from halt_core.interceptor.middleware import CommandInterceptor

# Create and configure the FastAPI application
app = FastAPI(
    title="Halt Core - Security Interceptor API",
    description="Security middleware sandbox designed to intercept, audit, and approve/deny actions generated by autonomous AI Agents.",
    version="1.0.0"
)

# Initialize memory tracking manager
memory_manager = MemoryManager()

# Initialize security rules
sql_deny_list = SQLDenyListRule()
shell_deny_list = ShellDenyListRule()
suspicious_sequence = SuspiciousSequenceRule()
semantic_intent = SemanticIntentRule()

# Initialize the modular security engine and register our initial policies
# The SemanticIntentRule is placed LAST to optimize compute latency (run only if regex/stateless checks pass)
security_engine = RuleEngine(rules=[sql_deny_list, shell_deny_list, suspicious_sequence, semantic_intent])

# Initialize the CommandInterceptor service (our security middleware broker)
command_interceptor = CommandInterceptor(rule_engine=security_engine, memory_manager=memory_manager)

@app.post(
    "/intercept", 
    response_model=SecurityDecision, 
    summary="Intercept and audit AI Agent Action",
    description="Evaluates the agent action against registered security rules. Returns approval status and remediation details if rejected."
)
async def intercept_action(action: AgentAction) -> SecurityDecision:
    """
    API endpoint where the agent or the executor framework submits commands for security clearance.
    """
    decision = command_interceptor.intercept(action)
    return decision

@app.get(
    "/health", 
    summary="Halt Core health check",
    description="Returns the status of Halt Core services."
)
async def health_check():
    return {
        "status": "healthy",
        "service": "halt-core",
        "active_rules": [sql_deny_list.name, shell_deny_list.name, suspicious_sequence.name, semantic_intent.name]
    }
